version: '3.3'
services:
  bear-feed-db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'bearfeed'
      MYSQL_ROOT_PASSWORD: 'sLT4NG#83UyK'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: