server:
  port: 8090

spring:
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092 #137.184.37.205:9094
    consumer:
      bootstrap-servers: 127.0.0.1:9092 #doc137.184.37.205:9094
      #group-id: contest-group
      auto-offset-reset: earliest