server:
  port: 8090

spring:
  kafka:
    producer:
      bootstrap-servers: 137.184.37.205:9094
    consumer:
      bootstrap-servers: 137.184.37.205:9094
      #group-id: contest-group
      auto-offset-reset: earliest