spring:
  datasource:
    #for localhost use this string jdbc:mysql://localhost:3306/bearfeed?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    url: jdbc:mysql://137.184.37.205:3306/bearfeed?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: sLT4NG#83UyK #change accordingly
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      #group-id: contest-group
      auto-offset-reset: earliest